using System;
namespace ORAGH.Models
{
    public class User
    {
        public string uid { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string salt { get; set; }
        public string loginkey { get; set; }
        public string email { get; set; }
        public string postnum { get; set; }
        public string threadnum { get; set; }
        public string avatar { get; set; }
        public string avatardimensions { get; set; }
        public string avatartype { get; set; }
        public string usergroup { get; set; }
        public string additionalgroups { get; set; }
        public string displaygroup { get; set; }
        public string usertitle { get; set; }
        public string regdate { get; set; }
        public string lastactive { get; set; }
        public string lastvisit { get; set; }
        public string lastpost { get; set; }
        public string website { get; set; }
        public string icq { get; set; }
        public string aim { get; set; }
        public string yahoo { get; set; }
        public string skype { get; set; }
        public string google { get; set; }
        public string birthday { get; set; }
        public string birthdayprivacy { get; set; }
        public string signature { get; set; }
        public string allownotices { get; set; }
        public string hideemail { get; set; }
        public string subscriptionmethod { get; set; }
        public string invisible { get; set; }
        public string receivepms { get; set; }
        public string receivefrombuddy { get; set; }
        public string pmnotice { get; set; }
        public string pmnotify { get; set; }
        public string buddyrequestspm { get; set; }
        public string buddyrequestsauto { get; set; }
        public string threadmode { get; set; }
        public string showimages { get; set; }
        public string showvideos { get; set; }
        public string showsigs { get; set; }
        public string showavatars { get; set; }
        public string showquickreply { get; set; }
        public string showredirect { get; set; }
        public string ppp { get; set; }
        public string tpp { get; set; }
        public string daysprune { get; set; }
        public string dateformat { get; set; }
        public string timeformat { get; set; }
        public string timezone { get; set; }
        public string dst { get; set; }
        public string dstcorrection { get; set; }
        public string buddylist { get; set; }
        public string ignorelist { get; set; }
        public string style { get; set; }
        public string away { get; set; }
        public string awaydate { get; set; }
        public string returndate { get; set; }
        public string awayreason { get; set; }
        public string pmfolders { get; set; }
        public string notepad { get; set; }
        public string referrer { get; set; }
        public string referrals { get; set; }
        public string reputation { get; set; }
        public string regip { get; set; }
        public string lastip { get; set; }
        public string language { get; set; }
        public string timeonline { get; set; }
        public string showcodebuttons { get; set; }
        public string totalpms { get; set; }
        public string unreadpms { get; set; }
        public string warningpoints { get; set; }
        public string moderateposts { get; set; }
        public string moderationtime { get; set; }
        public string suspendposting { get; set; }
        public string suspensiontime { get; set; }
        public string suspendsignature { get; set; }
        public string suspendsigtime { get; set; }
        public string coppauser { get; set; }
        public string classicpostbit { get; set; }
        public string loginattempts { get; set; }
        public string usernotes { get; set; }
        public string sourceeditor { get; set; }
        public string ufid { get; set; }
        public string fid1 { get; set; }
        public string fid4 { get; set; }
        public string fid5 { get; set; }
    }
}
